// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ0qPVIjKcxGV7E-Dkzr6crhEviDWUAHc',
    appId: '1:527996106083:web:ba9e00c895ff4941978f56',
    messagingSenderId: '527996106083',
    projectId: 'vocarise-universe',
    authDomain: 'vocarise-universe.firebaseapp.com',
    storageBucket: 'vocarise-universe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAENOQj6suVG_VHkmgvRiHo5AS4Zrcy4d0',
    appId: '1:527996106083:android:1e7e090cfa0580f4978f56',
    messagingSenderId: '527996106083',
    projectId: 'vocarise-universe',
    storageBucket: 'vocarise-universe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaLQ108y0HX9A49PatbCIjlBynR_bANwo',
    appId: '1:527996106083:ios:b0adde0374027f9b978f56',
    messagingSenderId: '527996106083',
    projectId: 'vocarise-universe',
    storageBucket: 'vocarise-universe.appspot.com',
    iosBundleId: 'com.example.vocariseFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaLQ108y0HX9A49PatbCIjlBynR_bANwo',
    appId: '1:527996106083:ios:459945793f54d56b978f56',
    messagingSenderId: '527996106083',
    projectId: 'vocarise-universe',
    storageBucket: 'vocarise-universe.appspot.com',
    iosBundleId: 'com.example.vocariseFinal.RunnerTests',
  );
}
